### ISSUE TITLE
Designing admin panel (clickable mock up)

### ISSUE THREAD

**Issue by luckosr** [angrynerds-pl/kpz-contactless-restaurant-frontend#1]

**Comment by luckosr** [comment]
link to figma: https://www.figma.com/file/XLQKZZgDktMDyCUYyJwlW1/KPZ-FRONT-MOCK-UP?node-id=0%3A1

**Comment by luckosr** [comment]
Prototyping (connetions between pages) added

**Comment by Carrmelooo** [comment]
Made visual corrections in user edit in a part of user editing

**Comment by luckosr** [comment]
Added editing restaurant info view

**Comment by Carrmelooo** [comment]
Added more pages in the admin panel, especially in the part of sub-account management.
