### ISSUE TITLE
Main admin panel page

### ISSUE THREAD

**Issue by luckosr** [angrynerds-pl/kpz-contactless-restaurant-frontend#3]
To do:
- [ ] Header with user data
- [ ] Navigation
- [ ] Restaurants managing component

**Comment by Devbhuti-Nandik** [comment]
Hello, I want to solve this issue as my first open-source contribution. Please provide the details and a bit of guidance regarding your issue. 
Thanks.

**Comment by luckosr** [comment]
I am really, but it is not an open source project really. We are developing this app on studies purposes so as you probably shouldn't take part in the process. Thanks for your interest. I wish you good luck with searching for nice open source project.
